# Generated by Django 5.1.7 on 2025-04-07 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='location',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='building_images',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='price_per_month',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='address',
            field=models.CharField(default='notwane road', max_length=255),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='bathrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='bedrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='city',
            field=models.CharField(default='Gaborone', max_length=100),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='property_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Hostel', 'Hostel'), ('Single Room', 'Single Room'), ('Shared Room', 'Shared Room')], default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='square_footage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='state',
            field=models.CharField(default='South East', max_length=100),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Coming Soon', 'Coming Soon')], default='Available', max_length=20),
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accommodations/')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='housing.accommodation')),
            ],
        ),
    ]
