# Generated by Django 5.1.7 on 2025-04-19 09:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_rename_location_accommodation_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodationimage',
            name='main_image',
            field=cloudinary.models.CloudinaryField(default='images/placeholder.jpg', max_length=255, verbose_name='main_image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accommodationimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
