# Generated by Django 5.1.7 on 2025-04-19 09:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_accommodationimage_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationimage',
            name='main_image',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='main_image',
            field=cloudinary.models.CloudinaryField(default='images/placeholder.jpg', max_length=255, verbose_name='Main Building Image'),
            preserve_default=False,
        ),
    ]
